#!/bin/bash
####################################
#
# Backup to NFS mount script.
#
####################################
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/cheezit_big_original/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/crayola_64_ct/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/dove_beauty_bar/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/dr_browns_bottle_brush/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/elmers_washable_no_run_school_glue/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/expo_dry_erase_board_eraser/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/feline_greenies_dental_treats/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/first_years_take_and_toss_straw_cups/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/genuine_joe_plastic_stir_sticks/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/highland_6539_self_stick_notes/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/kong_air_dog_squeakair_tennis_ball/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/kong_sitting_frog_dog_toy/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/kygen_squeakin_eggs_plush_puppies/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/laugh_out_loud_joke_book/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/mark_twain_huckleberry_finn/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/mead_index_cards/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/mommys_helper_outlet_plugs/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/munchkin_white_hot_duck_bath_toy/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/one_with_nature_soap_dead_sea_mud/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/oreo_mega_stuf/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/paper_mate_12_count_mirado_black_warrior/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/rollodex_mesh_collection_jumbo_pencil_cup/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/safety_works_safety_glasses/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/sharpie_accent_tank_style_highlighters/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/apc2015/stanley_66_052/meshes/tsdf.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/1_and_a_half_in_metal_washer/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/1in_metal_washer/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/2in_metal_washer/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/black_and_decker_lithium_drill_driver/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/black_and_decker_lithium_drill_driver_unboxed/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/blank_hard_plastic_card/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/block_of_wood_12in/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/block_of_wood_6in/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/blue_wood_block_1inx1in/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/brine_mini_soccer_ball/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/campbells_condensed_tomato_soup/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/champion_sports_official_softball/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/cheerios_14oz/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/cheeze-it_388g/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/clorox_disinfecting_wipes_35/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/comet_lemon_fresh_bleach/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/dark_red_foam_block_with_three_holes/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/domino_sugar_1lb/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/expo_black_dry_erase_marker/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/expo_black_dry_erase_marker_fine/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/extra_small_black_spring_clamp/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/frenchs_classic_yellow_mustard_14oz/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/jell-o_chocolate_flavor_pudding/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/jell-o_strawberry_gelatin_dessert/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/large_black_spring_clamp/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/learning_resources_one-inch_color_cubes_box/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/master_chef_ground_coffee_297g/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/medium_black_spring_clamp/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_apple/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_banana/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_lemon/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_orange/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_peach/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_pear/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_plum/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_farm_fresh_fruit_strawberry/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/melissa_doug_play-time_produce_farm_fresh_fruit_unopened_box/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/morton_pepper_shaker/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/morton_salt_shaker/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/moutain_security_steel_shackle/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/moutain_security_steel_shackle_key/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/orange_wood_block_1inx1in/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/penn_raquet_ball/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/plastic_bolt_grey/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/plastic_nut_grey/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/plastic_wine_cup/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_10_blue/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_1_yellow/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_2_orange/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_3_red/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_5_green/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_6_purple/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_7_yellow/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_8_orange/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_9_red/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_blue_4/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/play_go_rainbow_stakin_cups_box/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/pringles_original/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/purple_wood_block_1inx1in/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_metal_bowl_white_speckles/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_metal_cup_white_speckles/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_metal_plate_white_speckles/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/red_wood_block_1inx1in/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/rubbermaid_ice_guard_pitcher_blue/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sharpie_marker/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/small_black_spring_clamp/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/soft_scrub_2lb_4oz/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/spam_12oz/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sponge_with_textured_cover/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_fork_red_handle/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_knife_red_handle/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_spatula/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stainless_steel_spoon_red_handle/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stanley_13oz_hammer/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stanley_flathead_screwdriver/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/stanley_philips_screwdriver/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/starkist_chunk_light_tuna/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sterilite_bin_12qt_bottom/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/sterilite_bin_12qt_cap/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/thick_wood_block_6in/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wearever_cooking_pan_with_lid/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wescott_orange_grey_scissors/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/white_rope/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wilson_100_tennis_ball/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/wilson_golf_ball/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/windex/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/yellow_plastic_chain/meshes/tsdf_mesh.ply
./../build/mesh_decimator_example ~/manuelb_ws/src/Grasp-simulation/data/objects/ycb/yellow_wood_block_1inx1in/meshes/tsdf_mesh.ply 